
name: AddIn-build
run-name: triggered by ${{ github.actor }}

on: [ push ]
 
jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]
        #configuration: [Debug, Release]

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    # Execute all unit tests in the solution
    #- name: Execute unit tests
    #  run: dotnet test

    # Restore the application to populate the obj folder with RuntimeIdentifiers
    - name: Restore the application
      run: |
        cd AddIn
        msbuild /t:restore .\Itemis_Integrate_EA_Example_AddIn.sln /p:Configuration=Release
      env:
        Configuration: ${{ matrix.configuration }}

    # Create the app package by building and packaging the project
    - name: Create the app package
      run: |
        cd AddIn
        msbuild Itemis_Integrate_EA_Example_AddIn.sln /p:Configuration=Release /p:Platform="Any CPU" /detailedsummary /v:detailed
      env:
        Configuration: ${{ matrix.configuration }}

    # Upload the installer package
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Installer
        path: AddIn/Itemis_Integrate_EA_Example_AddIn_Setup/bin/x86/Release/*.msi
